repos:
  - repo: local
    hooks:
      - id: linting
        name: linting
        description: Run isort black flake8 pylint
        entry: bash -c "if [ -f .venv/bin/activate ]; then source .venv/bin/activate; fi && make format"
        language: python
        pass_filenames: false
        always_run: true
        verbose: true

      - id: small-tests
        name: small-tests
        description: Small-sized tests
        entry: bash -c "if [ -f .venv/bin/activate ]; then source .venv/bin/activate; fi && make test-small"
        language: python
        pass_filenames: false
        always_run: true
        verbose: true

      - id: requirements-sync
        name: requirements-sync
        description: Keep requirements.txt in sync with pyproject.toml
        entry: bash -c "if [ -f .venv/bin/activate ]; then source .venv/bin/activate; fi && make requirements"
        language: python
        files: pyproject.toml
        pass_filenames: false
        verbose: true
